// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAPa8M0drpwQUiWnPgbzl7DeIo-_vKuK4',
    appId: '1:588899843594:web:cfc3b8ad0444b325ef29f3',
    messagingSenderId: '588899843594',
    projectId: 'jalsetu-5a441',
    authDomain: 'jalsetu-5a441.firebaseapp.com',
    storageBucket: 'jalsetu-5a441.firebasestorage.app',
    measurementId: 'G-5KC1PEBH6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY-sxQIA5r6hpIUE1ZVmztZlLRZFb87rM',
    appId: '1:588899843594:android:a17e0daed274a657ef29f3',
    messagingSenderId: '588899843594',
    projectId: 'jalsetu-5a441',
    storageBucket: 'jalsetu-5a441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuN0Ob67vUg6NhkkoKjzk0j-eIFXjeYfM',
    appId: '1:588899843594:ios:3e58e8b15297cf0bef29f3',
    messagingSenderId: '588899843594',
    projectId: 'jalsetu-5a441',
    storageBucket: 'jalsetu-5a441.firebasestorage.app',
    iosBundleId: 'com.jalsetu.jalsetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuN0Ob67vUg6NhkkoKjzk0j-eIFXjeYfM',
    appId: '1:588899843594:ios:3e58e8b15297cf0bef29f3',
    messagingSenderId: '588899843594',
    projectId: 'jalsetu-5a441',
    storageBucket: 'jalsetu-5a441.firebasestorage.app',
    iosBundleId: 'com.jalsetu.jalsetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAPa8M0drpwQUiWnPgbzl7DeIo-_vKuK4',
    appId: '1:588899843594:web:941e4c50343ce6e1ef29f3',
    messagingSenderId: '588899843594',
    projectId: 'jalsetu-5a441',
    authDomain: 'jalsetu-5a441.firebaseapp.com',
    storageBucket: 'jalsetu-5a441.firebasestorage.app',
    measurementId: 'G-H00GK74LP0',
  );
}
